# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 205b0bc3a4ed4bad3ee49734f0745c1834ad97e99b4b928189e4762b1b53255a0628f81701205b753d5cb5ac43d5af43b1317df2faff045674fbd55a163506ca

test:
  secret_key_base: b00b5e0111eb733fa9af21a834010f8e77fd16dd4bda4fb73afdd3cd4a8e7718aa05a2cef1acc60aeb832a0e87d77e5a7361c5872aef30968979c17b5560044b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
